resources:
  - name: jatin_gitrepo2
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/pipelines
      branches:
       include: ^master$
  - name: jatin_pb
    type: PropertyBag
    configuration:
      foo: bar

#   - name: jatinimg
#     type:      Image
#     configuration:
#       registry: jatinart
#       sourceRepository: jatinart   # required if registry is Artifactory
#       imageName: jatin/jatin
#       imageTag: 1.0.0
# pipelines:
#   - name: jatin_custom_pipelines
#     steps:
#       - name: step_0
#         type: Bash
#         configuration:
#          inputResources:
#            - name: jatin_gitrepo2
#         execution:
#          onExecute:
#            - echo "hello"

#       - name: step_1
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_0
#         execution:
#          onExecute:
#            - echo "hello"

#       - name: step_2
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_0
#         execution:
#          onExecute:
#            - echo "hello"

#       - name: step_3
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_0
#         execution:
#          onExecute:
#            - echo "Hello world"
           
#       - name: step_4
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_0
#         execution:
#          onExecute:
#            - echo "Hello world"

#       - name: step_5
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_0
#         execution:
#          onExecute:
#            - echo "Hello world"
# resources:
#   - name: load_azure
#     type: CronTrigger
#     configuration:
#       interval: '*/10 * * * *'

pipelines:
  - name: load_pipeline
    steps:   
      - name: load_pipelines_bash
        type: Bash
        configuration:
          inputResources:
            - name: jatin_gitrepo2
        execution:
          onExecute:
            - echo "Hello World"

      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: load_pipelines_bash
          outputResources:
            - name: jatin_pb
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
        execution:
          onExecute:
            - echo "I am executing matrix steplet ${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"
 
  #       - name: load_pipelines_test2
#         type: Bash
# #         configuration:
# #           inputResources:
# #             - name: load_azure
              
#         execution:
#           onExecute:
#             - echo "This will run on one machine every 5 mins"
#       - name: load_pipelines_test3
#         type: Bash
# #         configuration:
# #           inputResources:
# #             - name: load_azure
              
#         execution:
#           onExecute:
#             - echo "This will run on one machine every 5 mins"
#       - name: load_pipelines_test4
#         type: Bash
# #         configuration:
# #           inputResources:
# #             - name: load_azure
              
#         execution:
#           onExecute:
#             - echo "This will run on one machine every 5 mins"
#       - name: load_pipelines_test5
#         type: Bash
# #         configuration:
# #           inputResources:
# #             - name: load_azure
              
#         execution:
#           onExecute:
#             - echo "This will run on one machine every 5 mins"
