resources:
  - name: jatin_gitrepo2
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/pipelines
pipelines:
  - name: jatin_custom_pipelines
    steps:  
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: jatin_gitrepo2
        execution:
         onExecute:
           - echo "foo=bar"
           - pushd $res_jatin_gitrepo2_resourcePath
           - ls
           - ls -lh
         onSuccess:
           - printenv
           - ls
           - pushd $res_jatin_gitrepo2_resourcePath
           - ls
           - ls -lh
#            - add_run_files state.txt state_file

#       - name: step_3
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_2
#         execution:
#          onExecute:
#            - echo "Hello world"
#            - restore_run_files state_file state.txt


 
