resources:
  - name: jatin_gitrepo2
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/pipelines
      branches:
       include: ^master$
pipelines:
  - name: jatin_custom_pipelines
    steps:  
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: jatin_gitrepo2
        execution:
         onExecute:
           - echo "hello"
         onSuccess:
           - printenv
           - ls
           - pushd $res_jatin_gitrepo2_resourcePath/test
           - add_run_files $res_jatin_gitrepo2_resourcePath/artifactory_pro_target_classes artifactory_pro_target_classes

      - name: step_3
        type: Bash
        configuration:
         inputSteps:
           - name: step_2
        execution:
         onStart:
           - stateFolder='restoredState'
           - mkdir -p $stateFolder
           - mkdir -p $stateFolder/classes
           - restore_run_files artifactory_pro_target_classes $stateFolder/classes
           - pushd $stateFolder/classes
           - ls
         onExecute:
           - sleep 20m
           - echo "Hello world"


 
