resources:
#   - name: buildInfoRes
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: artifactory
#       buildName: jatin
#       buildNumber: 1
#       externalCI: jenkins
      
pipelines:
  - name: load_pipeline
    configuration:
      nodePool: jatintest   
    steps:
#       - name: step_1
#         type: Bash
#         execution:
#           onStart:
#             - echo "this is onStart"
#             - restore_pipeline_files pipeline_state_file pipeline_state.txt
#             - echo "cache=file" > cachefile.txt
#             - add_cache_files cachefile.txt cache_file
#             - printenv
#           onExecute:
#             - echo "execute"
#           onSuccess:
#             - echo "this is onSuccess"
#           onComplete:
#             - echo "this is onComplete"
#           onFailure:
#             - echo "this is onFailure"

      - name: step_1
        type: Bash
        execution:
         onExecute:
           - sleep 2m
           - echo "Test"
