resources:
  - name: jatin_gitrepo2
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/pipelines
      branches:
       include: ^master$
pipelines:
  - name: jatin_custom_pipelines
    steps:
      - name: step_0
        type: Bash
        configuration:
         inputResources:
           - name: jatin_gitrepo2
        execution:
         onExecute:
           - echo "hello"

      - name: step_1
        type: Bash
        configuration:
         inputSteps:
           - name: step_0
        execution:
         onExecute:
           - echo "hello"

      - name: step_2
        type: Bash
        configuration:
         inputSteps:
           - name: step_0
        execution:
         onExecute:
           - echo "hello"

      - name: step_3
        type: Bash
        configuration:
         inputSteps:
           - name: step_0
        execution:
         onExecute:
           - echo "Hello world"
           
      - name: step_4
        type: Bash
        configuration:
         inputSteps:
           - name: step_0
        execution:
         onExecute:
           - echo "Hello world"

      - name: step_5
        type: Bash
        configuration:
         inputSteps:
           - name: step_0
        execution:
         onExecute:
           - echo "Hello world"
