pipelines:
  - name: jatin_custom_pipelines
    steps:  
      - name: step_2
        type: Bash
        configuration:
         inputResources:
           - name: buildInfoRes
        execution:
         onExecute:
           - echo "foo=bar"
         onSuccess:
           - printenv
#            - add_run_files state.txt state_file

#       - name: step_3
#         type: Bash
#         configuration:
#          inputSteps:
#            - name: step_2
#         execution:
#          onExecute:
#            - echo "Hello world"
#            - restore_run_files state_file state.txt


 
