resources:
  - name: jatin_gitrepo2
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/pipelines
      branches:
       include: ^master$
pipelines:
  - name: jatin_custom_pipelines
    steps:  
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: jatin_gitrepo2
        execution:
         onExecute:
           - echo "hello"
         onSuccess:
           - printenv
           - ls
           - pushd $res_jatin_gitrepo2_resourcePath/runState
           - add_run_files $res_jatin_gitrepo2_resourcePath/runState run_state

      - name: step_3
        type: Bash
        configuration:
         inputSteps:
           - name: step_2
        execution:
         onStart:
           - mkdir -p restoredState
           - restore_run_files run_state restoredState
           - pushd restoredState
           - ls
         onExecute:
           - echo "Hello world"


 
